#ifndef CONSTANTES 
#define CONSTANTES 

	#define MAX_NB_VOISINS_CELLULE 8 
	#define SEUIL_MAX_MORT 4
	#define SEUIL_MIN_MORT 2
	#define SEUIL_VIVANT 3
	#define NB_TOUR 1000
	#define LARGEUR_PLATEAU 20
	#define NB_CELLULE_VIVANTE_DEPART 50

#endif 
